### ISSUE TITLE
Altitude and Swift

### ISSUE THREAD

**Issue by gameboyzone** [ryancoughlin/Barometer-iOS#4]
Hello authors, I like your contribution and have a few questions -
1. Does this project also display altitude along with air pressure?
2. What best piece of advise would you give me if I have to convert this code to Swift?

**Comment by fcanas** [comment]
1. It does not display altitude, but that information is readily available and could be easily added to the output.
2. That depends entirely on your background and experience. There's not a lot of code here, so translating it line by line to Swift is feasible, and in my opinion a reasonable way to become comfortable with Swift. This application does not do a lot more than bridge existing Apple APIs to a UI, so direct translation would keep the resulting app the simplest. Keep in mind though that Swift has many features Objective-C does not, and you will not be learning anything about those (except optionals) by directly translating this code.

**Comment by gameboyzone** [comment]
Hello Fabian,

Thanks for your prompt response. I'm working on a similar small project for
retrieving the altitude from the Barometer sensor using Swift. I was
looking for a similar project when I came across yours.

I'll be starting today to work on that project. I'll post a link when I'm
done.

**Comment by gameboyzone** [comment]
Just an update - I have initialized a repository for an Altimeter-Motion Tracker in Swift. At the moment, I have untested code right now and would be testing on an actual iPhone 6/6+.

Feedback is welcome.

https://github.com/gameboyzone/AltiMo-Tracker

**Comment by fcanas** [comment]
@gameboyzone I hope this repository was useful to you. It looks like you are well on your way to getting something similar working in Swift. I've taken the plunge and have been writing primarily in Swift for about four months now. Let me know if there's anything specific you want advice on or need help with.

Happy hacking :)

**Comment by gameboyzone** [comment]
Hello Fabian,

Thanks for your response and assistance. I'll keep in touch.
